name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  install_dependencies:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: wyvox/action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        node-version: 18.17
    - run:  echo ${{ github.event.number }} > ./pr-number.txt
    - run: pnpm build
    - uses: actions/upload-artifact@v3
      with:
        name: deploy-prep-dist
        if-no-files-found: error
        path: .next
  
  deployment:
    name: "Deploy: Production"
    if: github.ref == 'refs/heads/main' 
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: install_dependencies
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1
        artifact_name: "deploy-prep-dist"
